In [1]:
import numpy as np
import os
import numpy.matlib

In [146]:
vec = np.array([[1,2,3,4,5.1,-6,7,8,9,10,11,-12]])
max_indx = np.argmax(vec)
max_indx


10

In [37]:
a = np.array([[1, 2], [3, 4]])
print(a)
print(a.T)
a.tolist()

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


[[1, 2], [3, 4]]

In [23]:
Mat = np.matrix([vec[0:4].tolist(),vec[4:8].tolist(),vec[8:12].tolist()])
Mat

matrix([[ 1,  2,  3,  4],
        [ 5, -6,  7,  8],
        [ 9, 10, 11, 12]])

In [24]:
vec[3:6].tolist()

[4, 5, -6]

In [25]:
Mat[0:3,1]

matrix([[ 2],
        [-6],
        [10]])

In [8]:
Mat

matrix([[ 1,  2,  3,  4],
        [ 5, -6,  7,  8],
        [ 9, 10, 11, 12]])

In [9]:
d = np.diag(Mat)

In [10]:
sig = np.sign(d)

In [11]:
np.diag(sig)

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0,  1]])

In [15]:
constraint_matrix = np.zeros((5 * 2, 12))
constraint_matrix.T

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [74]:
def MakeHomogeneous(pts, ax=0):
  assert(pts.ndim <= 2)
  assert(ax < pts.ndim)

  if pts.ndim == 2:
    num_pts = pts.shape[1-ax]
    if ax == 0:
      return np.append(pts, np.ones((1, num_pts)), ax)
    else:
      return np.append(pts, np.ones((num_pts, 1)), ax)

  else:
    return np.append(pts, 1)

In [81]:
def HNormalize(pts, ax=0):
  assert(pts.ndim <= 2)
  assert(ax < pts.ndim)

  if pts.ndim == 2:
    print("hello")
    if ax == 0:
      return pts[:-1,:] / pts[[-1], :]
    else:
      return pts[:,:-1] / pts[:, [-1]]

  else:
    return pts[:-1] / pts[-1]

In [87]:
pts = np.array([[0.5,0.2,0.6],[0.4,1,0.7],[2,1,3]])
print(pts)
print(pts.ndim)

[[0.5 0.2 0.6]
 [0.4 1.  0.7]
 [2.  1.  3. ]]
2


In [86]:
ptsN = HNormalize(pts, ax=0)
ptsN

hello


array([[0.25      , 0.2       , 0.2       ],
       [0.2       , 1.        , 0.23333333]])

In [91]:
pts2 = np.array([[0.5,0.2],[0.4,1]])
ptsH = MakeHomogeneous(pts2, ax=0)
print(pts2)
print(ptsH)
ptsN = HNormalize(ptsH, ax=0)
print(ptsN)

[[0.5 0.2]
 [0.4 1. ]]
[[0.5 0.2]
 [0.4 1. ]
 [1.  1. ]]
hello
[[0.5 0.2]
 [0.4 1. ]]


In [107]:
temp = np.random.rand(4,3)
temp

array([[0.7652656 , 0.12632392, 0.17835585],
       [0.37795525, 0.33770195, 0.76666532],
       [0.30917551, 0.42255446, 0.98080091],
       [0.62895276, 0.81430693, 0.20510072]])

In [115]:
temp = np.random.rand(4,3)
print("temp:", temp)
num = temp.shape[0]
print("temp.shape[0]: ",temp.shape[0])

for i in range(0,num,2):
    print(i)

temp: [[0.14945543 0.23809275 0.91276219]
 [0.92662148 0.76602442 0.70716459]
 [0.53876747 0.91425086 0.82647064]
 [0.14004957 0.63976591 0.79195685]]
temp.shape[0]:  4
0
2


In [2]:
what = {}
type(what)

dict

In [103]:
filekp1 = "/data/keypoints/0000.png.txt"
path = os.getcwd()+filekp1
kp1 = np.loadtxt(path)
#print("kp1",kp1.shape)

one = np.ones((kp1.shape[0],1))
kp1H = np.concatenate((kp1, one), axis = 1)
#print("kp1H", kp1H)

fileK = "/data/images/K.txt"
pathK = os.getcwd()+fileK
K = np.loadtxt(pathK)
#print("K",K)

K_inv = np.linalg.inv(K)
#print("K_inv", K_inv.shape)

np.set_printoptions(threshold=np.inf)
kp1N = np.dot(K_inv,kp1H.T)
kp1N_ = K_inv@kp1H.T
#print("kp1N", kp1N.shape)
#kp1N.T
np.allclose(kp1N,kp1N_)

True

kp1N (3, 4237)


array([[ 0.27669706, -0.35760231,  1.        ],
       [ 0.14922014, -0.35706688,  1.        ],
       [ 0.16362141, -0.35587665,  1.        ],
       ...,
       [ 0.22799948,  0.29618401,  1.        ],
       [ 0.34169119,  0.31585364,  1.        ],
       [ 0.11442736,  0.02586319,  1.        ]])

In [75]:
constraint_matrix = np.zeros((5, 9))
constraint_matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [80]:
constraint_matrix[1,:] = [1,2,3,4,-5,6,7,8,-9]
neun = constraint_matrix[1,:]
neun

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [81]:
np.reshape(neun, (3,3))

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [88]:
E_hat = np.array([[8.10e-4,-0.1594, 6.391e-4], [3.371e-02, -2.713e-02,  7.056e-01],  [2.070e-03, -6.886e-01, -2.775e-02]])
E_hat

array([[ 8.100e-04, -1.594e-01,  6.391e-04],
       [ 3.371e-02, -2.713e-02,  7.056e-01],
       [ 2.070e-03, -6.886e-01, -2.775e-02]])

In [98]:
u,s,vh = np.linalg.svd(E_hat)
print("u",u)
print("s",s)
print("vh",vh)
s[2] = 0
print("s zero",s)
E_reas = np.dot(u*s,vh)
print(E_reas)
np.allclose(E_hat,E_reas)

u [[-0.21044641  0.08060891 -0.97427641]
 [-0.39667065 -0.91790936  0.0097367 ]
 [-0.89351257  0.38851591  0.22514592]]
s [7.07406997e-01 7.06875402e-01 5.11817896e-06]
vh [[-0.02175805  0.93239053 -0.36079702]
 [-0.04254385 -0.36141905 -0.93143239]
 [ 0.99885765  0.00491646 -0.04753126]]
s zero [0.707407  0.7068754 0.       ]
[[ 8.14980825e-04 -1.59399975e-01  6.38862984e-04]
 [ 3.37099502e-02 -2.71300002e-02  7.05600002e-01]
 [ 2.06884898e-03 -6.88600006e-01 -2.77499452e-02]]


False

In [142]:
R = np.random.rand(3,3)
print(R)
t = np.array([3,1,2]).T
print(t)
T = np.append(R, np.expand_dims(t, 1), 1)

T = np.append(T, np.expand_dims([0,0,0,1],0), 0)
print("T2",T)


[[0.35067096 0.91132681 0.02939055]
 [0.02408278 0.77891254 0.54204828]
 [0.66801339 0.60694302 0.83561841]]
[3 1 2]
T2 [[0.35067096 0.91132681 0.02939055 3.        ]
 [0.02408278 0.77891254 0.54204828 1.        ]
 [0.66801339 0.60694302 0.83561841 2.        ]
 [0.         0.         0.         1.        ]]


In [143]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [166]:
R = np.random.randn(10,3)
corr = np.random.randn(1,10)
print("R",R)
r = R[R[:,2]>=0,:]
print("r",r)

idx = np.argwhere(R[:,2]<=0)
print(idx)
print(corr)

R [[-0.22942963  2.12694615 -1.94627459]
 [ 1.03397956  0.64702097  1.00394576]
 [-0.00323412  1.54231894 -0.18911568]
 [ 1.09220392  1.64080832 -0.27516103]
 [ 0.36501884 -0.03615568 -0.55894754]
 [-0.0662813  -0.25556682 -0.03629956]
 [ 0.49337581  1.25315434 -0.17028731]
 [-1.94076169  2.72085824 -0.36466621]
 [ 0.08962772 -1.59589238 -0.22232113]
 [-0.63639138  0.42656615  1.0840832 ]]
r [[ 1.03397956  0.64702097  1.00394576]
 [-0.63639138  0.42656615  1.0840832 ]]
[[0]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[-0.88413517  0.26885725 -0.48827145 -0.37294633 -0.68209473 -0.64210475
   0.01551328  1.29367428  2.93695187  2.77157938]]


In [167]:
corr_new =np.delete(corr,idx)
corr_new

array([0.26885725, 2.77157938])

In [3]:
K = np.array([[2759.48, 0.00, 1520.69],[0.00, 2764.16, 1006.81],[0.00, 0.00, 1.00]])
K

array([[2.75948e+03, 0.00000e+00, 1.52069e+03],
       [0.00000e+00, 2.76416e+03, 1.00681e+03],
       [0.00000e+00, 0.00000e+00, 1.00000e+00]])

In [22]:
K_inv = np.linalg.inv(K)
K_inv

array([[ 3.62387116e-04,  0.00000000e+00, -5.51078464e-01],
       [ 0.00000000e+00,  3.61773559e-04, -3.64237237e-01],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [26]:
xh = np.array([1984,9.91,1])
xh

array([1.984e+03, 9.910e+00, 1.000e+00])

In [27]:
x_norm = np.dot(K_inv,xh)
x_norm

array([ 0.16789757, -0.36065206,  1.        ])

In [28]:
np.dot( K_inv, xh.T).T

array([ 0.16789757, -0.36065206,  1.        ])

In [7]:
a = [1]
type(a)
if a:
    print("hello")

hello


In [27]:
D = np.zeros((0,3))
D
K = np.random.rand(1,3)
print(K)
Z = np.append(K,D,axis=0)
Z
P = np.random.rand(1,3)
L = np.append(Z,P,axis=0)
L

[[0.00803253 0.93257698 0.71940707]]


array([[0.00803253, 0.93257698, 0.71940707],
       [0.1373011 , 0.84316634, 0.46818359]])

In [38]:
corrs = {}
K = np.random.rand(1,3)
corrs["hello"] = {K[0,1:2]}
corrs

TypeError: unhashable type: 'numpy.ndarray'

In [45]:
from collections import defaultdict
my_dict = defaultdict(list)
dict = {}
type(dict)
dict["times"] = [1,2]
dict["times"].append([3,4])
dict

{'times': [1, 2, [3, 4]]}

In [6]:
a = []
a.append((1,2,3))
a

[(1, 2, 3)]

In [4]:
b=np.append(a,[3,2,4], axis=0)
b

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [19]:
dic = {'image1':np.array([[1,65],[2,704]]), 'image2':np.array([[3,5],[2,4]])}
dic

{'image1': array([[  1,  65],
        [  2, 704]]),
 'image2': array([[3, 5],
        [2, 4]])}

In [23]:
for i in dic:
    print(i)
    z = dic[i]
    type(z)
    print(z)
    print(z.shape)

image1
[[  1  65]
 [  2 704]]
(2, 2)
image2
[[3 5]
 [2 4]]
(2, 2)


In [84]:
l = [1,3,4,5]
u = [100,200,300,400]
points3D = np.array([l,u]).T
print(points3D)
new_points3D = np.array([4,300]) 
b = (points3D == new_points3D).all(axis=1)
print("b",b)
k = np.where(b)[0]
print(k)
idx = np.where((points3D == new_points3D).all(axis=1))[0][0]
print("idx",idx)

[[  1 100]
 [  3 200]
 [  4 300]
 [  5 400]]
b [False False  True False]
[2]
idx 2


In [42]:
idx_im = np.arange(0,10,1)
idx_im

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
points3D = np.random.rand(4,3)
points3D
idx_imquery = []

In [53]:
idx_imquery.append(points3D.shape[0])
idx_imquery

[4, 4, 4]

In [91]:
t = np.random.rand(3)
print(t.shape)
t = np.expand_dims(t,0)
print(t.shape)
t

(3,)
(1, 3)


array([[0.12842139, 0.42676106, 0.40771859]])

In [8]:
points3D = np.random.rand(4,3)
print(points3D)
new_points3D = np.random.rand(2,3)
print(new_points3D)
points3D = np.append(points3D, new_points3D, 0)
print(points3D)
points3D.shape[0]

[[0.99716096 0.16275563 0.2062707 ]
 [0.64549189 0.78444769 0.50945675]
 [0.37942652 0.54354385 0.46693881]
 [0.01662967 0.91939605 0.55669541]]
[[0.80925166 0.13096694 0.71203953]
 [0.22753752 0.18665482 0.22597579]]
[[0.99716096 0.16275563 0.2062707 ]
 [0.64549189 0.78444769 0.50945675]
 [0.37942652 0.54354385 0.46693881]
 [0.01662967 0.91939605 0.55669541]
 [0.80925166 0.13096694 0.71203953]
 [0.22753752 0.18665482 0.22597579]]


6